"""add problem uniqueness constraint

Revision ID: 00c915f23f51
Revises: 3c1873abaac4
Create Date: 2026-10-08 17:28:30.074072
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c915f23f51'
down_revision: Union[str, Sequence[str], None] = '3c1873abaac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_problem_platform_external_id', 'problems', ['platform_id', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_problem_platform_external_id', 'problems', type_='unique')
    # ### end Alembic commands ###