"""add user problem progress

Revision ID: 2b31ae982919
Revises: 00c915f23f51
Create Date: 2026-10-08 22:14:21.098153
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b31ae982919'
down_revision: Union[str, Sequence[str], None] = '00c915f23f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###